<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>029-promise对象的方法.html</title>
</head>
<body>
	
</body>
<script>
	const promise = new Promise((resolve,reject)=>{
		console.log('promise loading....')	
		setTimeout(function(){
			resolve('get data success')
			reject('get data fail...')
		},100)		
	})
	/*
	promise
	.then(data =>{
		console.log(data)
	},fail =>{
		console.log(fail)
	})
	*/
	promise
	.then(data =>{//resolved状态的回调，rejected状态的回调
		console.log(data);
	}).catch(fail =>{//如果异步操作抛出错误,状态就会变为rejected,当then中没有指定rejected状态的回调时就会调用catch方法指定的回调函数,如果运行中抛出错误，就会被catch方法捕捉
		console.log(fail);
	}).finally(()=>{//不管promise实列对象最后状态如何，都会执行的操作，finally方法的回调函数不接受任何参数
		console.log('finally...')
	})
</script>
</html>